import Head from "next/head";
import { useQuery } from "@apollo/client";
import { GET_ALL_ANIME } from "../graphql/animeQueries";
import AnimeList from "../components/AnimeList";

export default function Home() {
  const { loading, error, data } = useQuery(GET_ALL_ANIME, {
    variables: { page: 1, perPage: 10 },
  });

  const animes = data?.Page?.media || [];

  return (
    <>
      <Head>
        <title>Anime Collections</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AnimeList animes={animes} />
      </main>
    </>
  );
}
